### ISSUE TITLE
do.phenograph function introduces NA cluster exactly every 100'000 cells

### ISSUE THREAD

**Issue by JanaFischer** [BodenmillerGroup/bbRtools#12]
When using the do.phenograph wrapper on a large dataset (793'966 cells) with approx = T. It returns NA as cluster assignment exactly at cell 100000, 200000, 300000, 400000, 500000, 600000, 700000. This does not happen I use the cytofkit::Rphenograph function directly.

Here is how I called the function:
cluster_pheno = bbRtools::do_phenograph(dat, pheno_channels, valuevar='c_counts_perc_norm', idvar = 'id', k = 15, seed = rand_seed, approx=T)

I am using bbRtools version 0.4.

**Comment by votti** [comment]
Fixed with merge: 15bba7796663134782eb81ba48dc179476273ca6
